// Copyright (c) 2012-2018 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "json_generated.h"
#include "va.h"

#include "config.h"
#include "sb.h"
#include "sdict.h"

//////////////////////////////////////////////////////////////////////////

POINT json_deserialize_POINT(JSON_Value *src)
{
	POINT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.x = (LONG)json_object_get_number(obj, "x");
			dst.y = (LONG)json_object_get_number(obj, "y");
		}
	}
	return dst;
}

RECT json_deserialize_RECT(JSON_Value *src)
{
	RECT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.left = (LONG)json_object_get_number(obj, "left");
			dst.top = (LONG)json_object_get_number(obj, "top");
			dst.right = (LONG)json_object_get_number(obj, "right");
			dst.bottom = (LONG)json_object_get_number(obj, "bottom");
		}
	}
	return dst;
}

WINDOWPLACEMENT json_deserialize_WINDOWPLACEMENT(JSON_Value *src)
{
	WINDOWPLACEMENT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.length = (UINT)json_object_get_number(obj, "length");
			dst.flags = (UINT)json_object_get_number(obj, "flags");
			dst.showCmd = (UINT)json_object_get_number(obj, "showCmd");
			dst.ptMinPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMinPosition"));
			dst.ptMaxPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMaxPosition"));
			dst.rcNormalPosition = json_deserialize_RECT(json_object_get_value(obj, "rcNormalPosition"));
		}
	}
	return dst;
}

fontConfig_t json_deserialize_fontConfig_t(JSON_Value *src)
{
	fontConfig_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.enabled = json_object_get_boolean(obj, "enabled");
			dst.size = (u32)json_object_get_number(obj, "size");
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
		}
	}
	return dst;
}

uiChangelistConfig json_deserialize_uiChangelistConfig(JSON_Value *src)
{
	uiChangelistConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.descHeight = (float)json_object_get_number(obj, "descHeight");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.columnWidth); ++i) {
				dst.columnWidth[i] = (float)json_object_get_number(obj, va("columnWidth.%u", i));
			}
			dst.sortDescending = json_object_get_boolean(obj, "sortDescending");
			dst.sortColumn = (u32)json_object_get_number(obj, "sortColumn");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

uiChangesetConfig json_deserialize_uiChangesetConfig(JSON_Value *src)
{
	uiChangesetConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.columnWidth); ++i) {
				dst.columnWidth[i] = (float)json_object_get_number(obj, va("columnWidth.%u", i));
			}
			dst.sortDescending = json_object_get_boolean(obj, "sortDescending");
			dst.sortColumn = (u32)json_object_get_number(obj, "sortColumn");
		}
	}
	return dst;
}

diffConfig_t json_deserialize_diffConfig_t(JSON_Value *src)
{
	diffConfig_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.enabled = json_object_get_boolean(obj, "enabled");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
			dst.args = json_deserialize_sb_t(json_object_get_value(obj, "args"));
		}
	}
	return dst;
}

appTypeConfig json_deserialize_appTypeConfig(JSON_Value *src)
{
	appTypeConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.wp = json_deserialize_WINDOWPLACEMENT(json_object_get_value(obj, "wp"));
			dst.version = (u32)json_object_get_number(obj, "version");
		}
	}
	return dst;
}

config_t json_deserialize_config_t(JSON_Value *src)
{
	config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.logFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "logFontConfig"));
			dst.uiFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "uiFontConfig"));
			dst.uiChangelist = json_deserialize_uiChangelistConfig(json_object_get_value(obj, "uiChangelist"));
			dst.uiPendingChangesets = json_deserialize_uiChangesetConfig(json_object_get_value(obj, "uiPendingChangesets"));
			dst.uiSubmittedChangesets = json_deserialize_uiChangesetConfig(json_object_get_value(obj, "uiSubmittedChangesets"));
			dst.version = (u32)json_object_get_number(obj, "version");
			dst.diff = json_deserialize_diffConfig_t(json_object_get_value(obj, "diff"));
			dst.clientspec = json_deserialize_sb_t(json_object_get_value(obj, "clientspec"));
			dst.colorscheme = json_deserialize_sb_t(json_object_get_value(obj, "colorscheme"));
			dst.singleInstanceCheck = json_object_get_boolean(obj, "singleInstanceCheck");
			dst.singleInstancePrompt = json_object_get_boolean(obj, "singleInstancePrompt");
			dst.dpiAware = json_object_get_boolean(obj, "dpiAware");
			dst.doubleClickSeconds = (float)json_object_get_number(obj, "doubleClickSeconds");
			dst.dpiScale = (float)json_object_get_number(obj, "dpiScale");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

sdictEntry_t json_deserialize_sdictEntry_t(JSON_Value *src)
{
	sdictEntry_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.key = json_deserialize_sb_t(json_object_get_value(obj, "key"));
			dst.value = json_deserialize_sb_t(json_object_get_value(obj, "value"));
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_POINT(const POINT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "x", src->x);
		json_object_set_number(obj, "y", src->y);
	}
	return val;
}

JSON_Value *json_serialize_RECT(const RECT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "left", src->left);
		json_object_set_number(obj, "top", src->top);
		json_object_set_number(obj, "right", src->right);
		json_object_set_number(obj, "bottom", src->bottom);
	}
	return val;
}

JSON_Value *json_serialize_WINDOWPLACEMENT(const WINDOWPLACEMENT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "length", src->length);
		json_object_set_number(obj, "flags", src->flags);
		json_object_set_number(obj, "showCmd", src->showCmd);
		json_object_set_value(obj, "ptMinPosition", json_serialize_POINT(&src->ptMinPosition));
		json_object_set_value(obj, "ptMaxPosition", json_serialize_POINT(&src->ptMaxPosition));
		json_object_set_value(obj, "rcNormalPosition", json_serialize_RECT(&src->rcNormalPosition));
	}
	return val;
}

JSON_Value *json_serialize_fontConfig_t(const fontConfig_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "enabled", src->enabled);
		json_object_set_number(obj, "size", src->size);
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
	}
	return val;
}

JSON_Value *json_serialize_uiChangelistConfig(const uiChangelistConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "descHeight", src->descHeight);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->columnWidth); ++i) {
			json_object_set_number(obj, va("columnWidth.%u", i), src->columnWidth[i]);
		}
		json_object_set_boolean(obj, "sortDescending", src->sortDescending);
		json_object_set_number(obj, "sortColumn", src->sortColumn);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_uiChangesetConfig(const uiChangesetConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		for(u32 i = 0; i < BB_ARRAYSIZE(src->columnWidth); ++i) {
			json_object_set_number(obj, va("columnWidth.%u", i), src->columnWidth[i]);
		}
		json_object_set_boolean(obj, "sortDescending", src->sortDescending);
		json_object_set_number(obj, "sortColumn", src->sortColumn);
	}
	return val;
}

JSON_Value *json_serialize_diffConfig_t(const diffConfig_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "enabled", src->enabled);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
		json_object_set_value(obj, "args", json_serialize_sb_t(&src->args));
	}
	return val;
}

JSON_Value *json_serialize_appTypeConfig(const appTypeConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "wp", json_serialize_WINDOWPLACEMENT(&src->wp));
		json_object_set_number(obj, "version", src->version);
	}
	return val;
}

JSON_Value *json_serialize_config_t(const config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "logFontConfig", json_serialize_fontConfig_t(&src->logFontConfig));
		json_object_set_value(obj, "uiFontConfig", json_serialize_fontConfig_t(&src->uiFontConfig));
		json_object_set_value(obj, "uiChangelist", json_serialize_uiChangelistConfig(&src->uiChangelist));
		json_object_set_value(obj, "uiPendingChangesets", json_serialize_uiChangesetConfig(&src->uiPendingChangesets));
		json_object_set_value(obj, "uiSubmittedChangesets", json_serialize_uiChangesetConfig(&src->uiSubmittedChangesets));
		json_object_set_number(obj, "version", src->version);
		json_object_set_value(obj, "diff", json_serialize_diffConfig_t(&src->diff));
		json_object_set_value(obj, "clientspec", json_serialize_sb_t(&src->clientspec));
		json_object_set_value(obj, "colorscheme", json_serialize_sb_t(&src->colorscheme));
		json_object_set_boolean(obj, "singleInstanceCheck", src->singleInstanceCheck);
		json_object_set_boolean(obj, "singleInstancePrompt", src->singleInstancePrompt);
		json_object_set_boolean(obj, "dpiAware", src->dpiAware);
		json_object_set_number(obj, "doubleClickSeconds", src->doubleClickSeconds);
		json_object_set_number(obj, "dpiScale", src->dpiScale);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_sdictEntry_t(const sdictEntry_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "key", json_serialize_sb_t(&src->key));
		json_object_set_value(obj, "value", json_serialize_sb_t(&src->value));
	}
	return val;
}

//////////////////////////////////////////////////////////////////////////
