// Copyright (c) 2012-2019 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#pragma once

#include "bb_types.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef struct sb_s sb_t;
typedef struct sbs_s sbs_t;
typedef struct sdictEntry_s sdictEntry_t;
typedef struct sdict_s sdict_t;
typedef struct uuid_node_s uuid_node_t;
typedef struct fontConfig_s fontConfig_t;
typedef struct fontConfigs_s fontConfigs_t;
typedef struct tagPOINT POINT;
typedef struct tagRECT RECT;
typedef struct tagWINDOWPLACEMENT WINDOWPLACEMENT;
typedef struct tag_uiChangelistConfig uiChangelistConfig;
typedef struct tag_uiChangesetConfig uiChangesetConfig;
typedef struct diffConfig_s diffConfig_t;
typedef struct tag_appTypeConfig appTypeConfig;
typedef struct tag_p4Config p4Config;
typedef struct tag_changelistConfig changelistConfig;
typedef struct tag_changesetConfig changesetConfig;
typedef struct tag_tabConfig tabConfig;
typedef struct tag_tabsConfig tabsConfig;
typedef struct tag_updatesConfig updatesConfig;
typedef struct config_s config_t;
typedef struct updateConfig_s updateConfig_t;
typedef struct site_config_s site_config_t;

void sb_reset_from_loc(const char *file, int line, sb_t *val);
void sbs_reset_from_loc(const char *file, int line, sbs_t *val);
void sdictEntry_reset(sdictEntry_t *val);
void sdict_reset(sdict_t *val);
void uuid_node_reset(uuid_node_t *val);
void fontConfig_reset(fontConfig_t *val);
void fontConfigs_reset(fontConfigs_t *val);
void POINT_reset(POINT *val);
void RECT_reset(RECT *val);
void WINDOWPLACEMENT_reset(WINDOWPLACEMENT *val);
void uiChangelistConfig_reset(uiChangelistConfig *val);
void uiChangesetConfig_reset(uiChangesetConfig *val);
void diffConfig_reset(diffConfig_t *val);
void appTypeConfig_reset(appTypeConfig *val);
void p4Config_reset(p4Config *val);
void changelistConfig_reset(changelistConfig *val);
void changesetConfig_reset(changesetConfig *val);
void tabConfig_reset(tabConfig *val);
void tabsConfig_reset(tabsConfig *val);
void updatesConfig_reset(updatesConfig *val);
void config_reset(config_t *val);
void updateConfig_reset(updateConfig_t *val);
void site_config_reset(site_config_t *val);

sb_t sb_clone_from_loc(const char *file, int line, const sb_t *src);
sbs_t sbs_clone_from_loc(const char *file, int line, const sbs_t *src);
sdictEntry_t sdictEntry_clone(const sdictEntry_t *src);
sdict_t sdict_clone(const sdict_t *src);
uuid_node_t uuid_node_clone(const uuid_node_t *src);
fontConfig_t fontConfig_clone(const fontConfig_t *src);
fontConfigs_t fontConfigs_clone(const fontConfigs_t *src);
POINT POINT_clone(const POINT *src);
RECT RECT_clone(const RECT *src);
WINDOWPLACEMENT WINDOWPLACEMENT_clone(const WINDOWPLACEMENT *src);
uiChangelistConfig uiChangelistConfig_clone(const uiChangelistConfig *src);
uiChangesetConfig uiChangesetConfig_clone(const uiChangesetConfig *src);
diffConfig_t diffConfig_clone(const diffConfig_t *src);
appTypeConfig appTypeConfig_clone(const appTypeConfig *src);
p4Config p4Config_clone(const p4Config *src);
changelistConfig changelistConfig_clone(const changelistConfig *src);
changesetConfig changesetConfig_clone(const changesetConfig *src);
tabConfig tabConfig_clone(const tabConfig *src);
tabsConfig tabsConfig_clone(const tabsConfig *src);
updatesConfig updatesConfig_clone(const updatesConfig *src);
config_t config_clone(const config_t *src);
updateConfig_t updateConfig_clone(const updateConfig_t *src);
site_config_t site_config_clone(const site_config_t *src);

#if defined(__cplusplus)
} // extern "C"
#endif

#if !defined(sb_reset)
#define sb_reset(var) sb_reset_from_loc(__FILE__, __LINE__, var);
#endif
#if !defined(sbs_reset)
#define sbs_reset(var) sbs_reset_from_loc(__FILE__, __LINE__, var);
#endif

#if !defined(sb_clone)
#define sb_clone(var) sb_clone_from_loc(__FILE__, __LINE__, var);
#endif
#if !defined(sbs_clone)
#define sbs_clone(var) sbs_clone_from_loc(__FILE__, __LINE__, var);
#endif
