// Copyright (c) 2012-2019 Matt Campbell
// MIT license (see License.txt)

// AUTOGENERATED FILE - DO NOT EDIT

// clang-format off

#include "p4t_json_generated.h"
#include "bb_array.h"
#include "json_utils.h"
#include "va.h"

#include "config.h"
#include "fonts.h"
#include "sb.h"
#include "sdict.h"
#include "site_config.h"
#include "uuid_rfc4122/sysdep.h"

//////////////////////////////////////////////////////////////////////////

POINT json_deserialize_POINT(JSON_Value *src)
{
	POINT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.x = (LONG)json_object_get_number(obj, "x");
			dst.y = (LONG)json_object_get_number(obj, "y");
		}
	}
	return dst;
}

RECT json_deserialize_RECT(JSON_Value *src)
{
	RECT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.left = (LONG)json_object_get_number(obj, "left");
			dst.top = (LONG)json_object_get_number(obj, "top");
			dst.right = (LONG)json_object_get_number(obj, "right");
			dst.bottom = (LONG)json_object_get_number(obj, "bottom");
		}
	}
	return dst;
}

WINDOWPLACEMENT json_deserialize_WINDOWPLACEMENT(JSON_Value *src)
{
	WINDOWPLACEMENT dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.length = (UINT)json_object_get_number(obj, "length");
			dst.flags = (UINT)json_object_get_number(obj, "flags");
			dst.showCmd = (UINT)json_object_get_number(obj, "showCmd");
			dst.ptMinPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMinPosition"));
			dst.ptMaxPosition = json_deserialize_POINT(json_object_get_value(obj, "ptMaxPosition"));
			dst.rcNormalPosition = json_deserialize_RECT(json_object_get_value(obj, "rcNormalPosition"));
		}
	}
	return dst;
}

uiChangelistConfig json_deserialize_uiChangelistConfig(JSON_Value *src)
{
	uiChangelistConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.descHeight = (float)json_object_get_number(obj, "descHeight");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.columnWidth); ++i) {
				dst.columnWidth[i] = (float)json_object_get_number(obj, va("columnWidth.%u", i));
			}
			dst.sortDescending = json_object_get_boolean_safe(obj, "sortDescending");
			dst.sortColumn = (u32)json_object_get_number(obj, "sortColumn");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

uiChangesetConfig json_deserialize_uiChangesetConfig(JSON_Value *src)
{
	uiChangesetConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.columnWidth); ++i) {
				dst.columnWidth[i] = (float)json_object_get_number(obj, va("columnWidth.%u", i));
			}
			dst.sortDescending = json_object_get_boolean_safe(obj, "sortDescending");
			dst.sortColumn = (u32)json_object_get_number(obj, "sortColumn");
		}
	}
	return dst;
}

diffConfig_t json_deserialize_diffConfig_t(JSON_Value *src)
{
	diffConfig_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.enabled = json_object_get_boolean_safe(obj, "enabled");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
			dst.path = json_deserialize_sb_t(json_object_get_value(obj, "path"));
			dst.args = json_deserialize_sb_t(json_object_get_value(obj, "args"));
		}
	}
	return dst;
}

appTypeConfig json_deserialize_appTypeConfig(JSON_Value *src)
{
	appTypeConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.wp = json_deserialize_WINDOWPLACEMENT(json_object_get_value(obj, "wp"));
			dst.version = (u32)json_object_get_number(obj, "version");
		}
	}
	return dst;
}

p4Config json_deserialize_p4Config(JSON_Value *src)
{
	p4Config dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.clientspec = json_deserialize_sb_t(json_object_get_value(obj, "clientspec"));
			dst.changelistBlockSize = (u32)json_object_get_number(obj, "changelistBlockSize");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

changelistConfig json_deserialize_changelistConfig(JSON_Value *src)
{
	changelistConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.number = (u32)json_object_get_number(obj, "number");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

changesetConfig json_deserialize_changesetConfig(JSON_Value *src)
{
	changesetConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.pending = json_object_get_boolean_safe(obj, "pending");
			dst.filterEnabled = json_object_get_boolean_safe(obj, "filterEnabled");
			dst.user = json_deserialize_sb_t(json_object_get_value(obj, "user"));
			dst.clientspec = json_deserialize_sb_t(json_object_get_value(obj, "clientspec"));
			dst.filter = json_deserialize_sb_t(json_object_get_value(obj, "filter"));
			dst.filterInput = json_deserialize_sb_t(json_object_get_value(obj, "filterInput"));
		}
	}
	return dst;
}

tabConfig json_deserialize_tabConfig(JSON_Value *src)
{
	tabConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.isChangeset = json_object_get_boolean_safe(obj, "isChangeset");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
			dst.cl = json_deserialize_changelistConfig(json_object_get_value(obj, "cl"));
			dst.cs = json_deserialize_changesetConfig(json_object_get_value(obj, "cs"));
		}
	}
	return dst;
}

tabsConfig json_deserialize_tabsConfig(JSON_Value *src)
{
	tabsConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Array *arr = json_value_get_array(src);
		if(arr) {
			for(u32 i = 0; i < json_array_get_count(arr); ++i) {
				bba_push(dst, json_deserialize_tabConfig(json_array_get_value(arr, i)));
			}
		}
	}
	return dst;
}

updatesConfig json_deserialize_updatesConfig(JSON_Value *src)
{
	updatesConfig dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.waitForDebugger = json_object_get_boolean_safe(obj, "waitForDebugger");
			dst.pauseAfterSuccess = json_object_get_boolean_safe(obj, "pauseAfterSuccess");
			dst.pauseAfterFailure = json_object_get_boolean_safe(obj, "pauseAfterFailure");
			dst.showManagement = json_object_get_boolean_safe(obj, "showManagement");
		}
	}
	return dst;
}

config_t json_deserialize_config_t(JSON_Value *src)
{
	config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.logFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "logFontConfig"));
			dst.uiFontConfig = json_deserialize_fontConfig_t(json_object_get_value(obj, "uiFontConfig"));
			dst.tabs = json_deserialize_tabsConfig(json_object_get_value(obj, "tabs"));
			dst.uiChangelist = json_deserialize_uiChangelistConfig(json_object_get_value(obj, "uiChangelist"));
			dst.uiPendingChangesets = json_deserialize_uiChangesetConfig(json_object_get_value(obj, "uiPendingChangesets"));
			dst.uiSubmittedChangesets = json_deserialize_uiChangesetConfig(json_object_get_value(obj, "uiSubmittedChangesets"));
			dst.updates = json_deserialize_updatesConfig(json_object_get_value(obj, "updates"));
			dst.version = (u32)json_object_get_number(obj, "version");
			dst.diff = json_deserialize_diffConfig_t(json_object_get_value(obj, "diff"));
			dst.colorscheme = json_deserialize_sb_t(json_object_get_value(obj, "colorscheme"));
			dst.p4 = json_deserialize_p4Config(json_object_get_value(obj, "p4"));
			dst.singleInstanceCheck = json_object_get_boolean_safe(obj, "singleInstanceCheck");
			dst.singleInstancePrompt = json_object_get_boolean_safe(obj, "singleInstancePrompt");
			dst.dpiAware = json_object_get_boolean_safe(obj, "dpiAware");
			dst.doubleClickSeconds = (float)json_object_get_number(obj, "doubleClickSeconds");
			dst.dpiScale = (float)json_object_get_number(obj, "dpiScale");
			dst.activeTab = (u32)json_object_get_number(obj, "activeTab");
			dst.bDocking = json_object_get_boolean_safe(obj, "bDocking");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

updateConfig_t json_deserialize_updateConfig_t(JSON_Value *src)
{
	updateConfig_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.updateResultDir = json_deserialize_sb_t(json_object_get_value(obj, "updateResultDir"));
			dst.updateManifestDir = json_deserialize_sb_t(json_object_get_value(obj, "updateManifestDir"));
			dst.updateCheckMs = (u32)json_object_get_number(obj, "updateCheckMs");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

site_config_t json_deserialize_site_config_t(JSON_Value *src)
{
	site_config_t dst;
	memset(&dst, 0, sizeof(dst));
	if(src) {
		JSON_Object *obj = json_value_get_object(src);
		if(obj) {
			dst.updates = json_deserialize_updateConfig_t(json_object_get_value(obj, "updates"));
			dst.bugAssignee = json_deserialize_sb_t(json_object_get_value(obj, "bugAssignee"));
			dst.bugProject = json_deserialize_sb_t(json_object_get_value(obj, "bugProject"));
			dst.bugPort = (u16)json_object_get_number(obj, "bugPort");
			for(u32 i = 0; i < BB_ARRAYSIZE(dst.pad); ++i) {
				dst.pad[i] = (u8)json_object_get_number(obj, va("pad.%u", i));
			}
		}
	}
	return dst;
}

//////////////////////////////////////////////////////////////////////////

JSON_Value *json_serialize_POINT(const POINT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "x", src->x);
		json_object_set_number(obj, "y", src->y);
	}
	return val;
}

JSON_Value *json_serialize_RECT(const RECT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "left", src->left);
		json_object_set_number(obj, "top", src->top);
		json_object_set_number(obj, "right", src->right);
		json_object_set_number(obj, "bottom", src->bottom);
	}
	return val;
}

JSON_Value *json_serialize_WINDOWPLACEMENT(const WINDOWPLACEMENT *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "length", src->length);
		json_object_set_number(obj, "flags", src->flags);
		json_object_set_number(obj, "showCmd", src->showCmd);
		json_object_set_value(obj, "ptMinPosition", json_serialize_POINT(&src->ptMinPosition));
		json_object_set_value(obj, "ptMaxPosition", json_serialize_POINT(&src->ptMaxPosition));
		json_object_set_value(obj, "rcNormalPosition", json_serialize_RECT(&src->rcNormalPosition));
	}
	return val;
}

JSON_Value *json_serialize_uiChangelistConfig(const uiChangelistConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "descHeight", src->descHeight);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->columnWidth); ++i) {
			json_object_set_number(obj, va("columnWidth.%u", i), src->columnWidth[i]);
		}
		json_object_set_boolean(obj, "sortDescending", src->sortDescending);
		json_object_set_number(obj, "sortColumn", src->sortColumn);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_uiChangesetConfig(const uiChangesetConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		for(u32 i = 0; i < BB_ARRAYSIZE(src->columnWidth); ++i) {
			json_object_set_number(obj, va("columnWidth.%u", i), src->columnWidth[i]);
		}
		json_object_set_boolean(obj, "sortDescending", src->sortDescending);
		json_object_set_number(obj, "sortColumn", src->sortColumn);
	}
	return val;
}

JSON_Value *json_serialize_diffConfig_t(const diffConfig_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "enabled", src->enabled);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
		json_object_set_value(obj, "path", json_serialize_sb_t(&src->path));
		json_object_set_value(obj, "args", json_serialize_sb_t(&src->args));
	}
	return val;
}

JSON_Value *json_serialize_appTypeConfig(const appTypeConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "wp", json_serialize_WINDOWPLACEMENT(&src->wp));
		json_object_set_number(obj, "version", src->version);
	}
	return val;
}

JSON_Value *json_serialize_p4Config(const p4Config *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "clientspec", json_serialize_sb_t(&src->clientspec));
		json_object_set_number(obj, "changelistBlockSize", src->changelistBlockSize);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_changelistConfig(const changelistConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_number(obj, "number", src->number);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_changesetConfig(const changesetConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "pending", src->pending);
		json_object_set_boolean(obj, "filterEnabled", src->filterEnabled);
		json_object_set_value(obj, "user", json_serialize_sb_t(&src->user));
		json_object_set_value(obj, "clientspec", json_serialize_sb_t(&src->clientspec));
		json_object_set_value(obj, "filter", json_serialize_sb_t(&src->filter));
		json_object_set_value(obj, "filterInput", json_serialize_sb_t(&src->filterInput));
	}
	return val;
}

JSON_Value *json_serialize_tabConfig(const tabConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "isChangeset", src->isChangeset);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
		json_object_set_value(obj, "cl", json_serialize_changelistConfig(&src->cl));
		json_object_set_value(obj, "cs", json_serialize_changesetConfig(&src->cs));
	}
	return val;
}

JSON_Value *json_serialize_tabsConfig(const tabsConfig *src)
{
	JSON_Value *val = json_value_init_array();
	JSON_Array *arr = json_value_get_array(val);
	if(arr) {
		for(u32 i = 0; i < src->count; ++i) {
			JSON_Value *child = json_serialize_tabConfig(src->data + i);
			if(child) {
				json_array_append_value(arr, child);
			}
		}
	}
	return val;
}

JSON_Value *json_serialize_updatesConfig(const updatesConfig *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_boolean(obj, "waitForDebugger", src->waitForDebugger);
		json_object_set_boolean(obj, "pauseAfterSuccess", src->pauseAfterSuccess);
		json_object_set_boolean(obj, "pauseAfterFailure", src->pauseAfterFailure);
		json_object_set_boolean(obj, "showManagement", src->showManagement);
	}
	return val;
}

JSON_Value *json_serialize_config_t(const config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "logFontConfig", json_serialize_fontConfig_t(&src->logFontConfig));
		json_object_set_value(obj, "uiFontConfig", json_serialize_fontConfig_t(&src->uiFontConfig));
		json_object_set_value(obj, "tabs", json_serialize_tabsConfig(&src->tabs));
		json_object_set_value(obj, "uiChangelist", json_serialize_uiChangelistConfig(&src->uiChangelist));
		json_object_set_value(obj, "uiPendingChangesets", json_serialize_uiChangesetConfig(&src->uiPendingChangesets));
		json_object_set_value(obj, "uiSubmittedChangesets", json_serialize_uiChangesetConfig(&src->uiSubmittedChangesets));
		json_object_set_value(obj, "updates", json_serialize_updatesConfig(&src->updates));
		json_object_set_number(obj, "version", src->version);
		json_object_set_value(obj, "diff", json_serialize_diffConfig_t(&src->diff));
		json_object_set_value(obj, "colorscheme", json_serialize_sb_t(&src->colorscheme));
		json_object_set_value(obj, "p4", json_serialize_p4Config(&src->p4));
		json_object_set_boolean(obj, "singleInstanceCheck", src->singleInstanceCheck);
		json_object_set_boolean(obj, "singleInstancePrompt", src->singleInstancePrompt);
		json_object_set_boolean(obj, "dpiAware", src->dpiAware);
		json_object_set_number(obj, "doubleClickSeconds", src->doubleClickSeconds);
		json_object_set_number(obj, "dpiScale", src->dpiScale);
		json_object_set_number(obj, "activeTab", src->activeTab);
		json_object_set_boolean(obj, "bDocking", src->bDocking);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_updateConfig_t(const updateConfig_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "updateResultDir", json_serialize_sb_t(&src->updateResultDir));
		json_object_set_value(obj, "updateManifestDir", json_serialize_sb_t(&src->updateManifestDir));
		json_object_set_number(obj, "updateCheckMs", src->updateCheckMs);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

JSON_Value *json_serialize_site_config_t(const site_config_t *src)
{
	JSON_Value *val = json_value_init_object();
	JSON_Object *obj = json_value_get_object(val);
	if(obj) {
		json_object_set_value(obj, "updates", json_serialize_updateConfig_t(&src->updates));
		json_object_set_value(obj, "bugAssignee", json_serialize_sb_t(&src->bugAssignee));
		json_object_set_value(obj, "bugProject", json_serialize_sb_t(&src->bugProject));
		json_object_set_number(obj, "bugPort", src->bugPort);
		for(u32 i = 0; i < BB_ARRAYSIZE(src->pad); ++i) {
			json_object_set_number(obj, va("pad.%u", i), src->pad[i]);
		}
	}
	return val;
}

//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////
